import type { AiJobType } from '../aiJobs/types';
import type { AiTaskCatalogEntry } from './types';

const TASK_CATALOG_VERSION = 'v1';

const CURRENT_TASK_CATALOG: AiTaskCatalogEntry[] = [
    {
        taskType: 'discussion.analysis.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'rule_then_llm_boundary_judge',
        requiredCapabilities: ['text.embed', 'text.classify', 'text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/discussion',
        aiJobType: 'discussion_message_analyze',
    },
    {
        taskType: 'discussion.reanalyze.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'embedding_retrieval',
        requiredCapabilities: ['text.embed'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/discussion',
        aiJobType: 'discussion_circle_reanalyze',
    },
    {
        taskType: 'discussion.trigger.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'rule_then_llm_boundary_judge',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/ai/discussion-draft-trigger.ts',
        aiJobType: 'discussion_trigger_evaluate',
    },
    {
        taskType: 'discussion.summary.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/ai/discussion-summary.ts',
        aiJobType: null,
    },
    {
        taskType: 'draft.ghost_revision.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure', 'text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/ai/ghost-draft.ts',
        aiJobType: 'ghost_draft_generate',
    },
    {
        taskType: 'draft.accepted_issue_revision.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure', 'text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/draftAiAssist/acceptedIssueRevision.ts',
        aiJobType: 'accepted_issue_revision_generate',
    },
    {
        taskType: 'place_prompt.trend_aware.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure', 'text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'frontend/src/components/circle/CreateCircleSheet/CreateCircleSheet.tsx',
        aiJobType: 'trend_prompt_generate',
    },
    {
        taskType: 'configuration.copilot.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure', 'text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'frontend/src/components/alcheme/ConfigurationDiffPanel/ConfigurationDiffPanel.tsx',
        aiJobType: 'configuration_copilot_generate',
    },
    {
        taskType: 'settings.field_text_suggestion.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'frontend/src/components/alcheme/FieldAssist/FieldAssistInline.tsx',
        aiJobType: 'settings_text_assist_generate',
    },
    {
        taskType: 'style.life_feel_advisor.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/style',
        aiJobType: 'style_life_feel_generate',
    },
    {
        taskType: 'anchored.interaction_suggestion_judge.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/anchoredSuggestions',
        aiJobType: 'anchored_interaction_suggestion_judge',
    },
    {
        taskType: 'knowledge.relationship_label_classify.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/knowledgeRelationshipLabelAi',
        aiJobType: 'knowledge_relationship_label_classify',
    },
    {
        taskType: 'knowledge.relationship_label_coverage_audit.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/knowledgeRelationshipLabelAi',
        aiJobType: 'knowledge_relationship_label_coverage_audit',
    },
    {
        taskType: 'circle.cognitive_map_explain.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/cognitiveMap',
        aiJobType: 'circle_cognitive_map_explain',
    },
    {
        taskType: 'contribution.assessment_suggest.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/contributionAssessment',
        aiJobType: null,
    },
    {
        taskType: 'guardian.finding.watch.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'deterministic_only',
        requiredCapabilities: [],
        allowedProviderProfiles: [],
        promptVersion: null,
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/guardian',
        aiJobType: 'guardian_finding_generate',
    },
    {
        taskType: 'source.grounded_ask.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/sourceGroundedAsk',
        aiJobType: 'source_grounded_ask_generate',
    },
    {
        taskType: 'evaluation.neutral.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/evaluation',
        aiJobType: 'neutral_evaluation_generate',
    },
    {
        taskType: 'circle.growth_advisor.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'llm_structured_generate',
        requiredCapabilities: ['text.structure'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/aiOperatingLayer/growth',
        aiJobType: 'circle_growth_advisor_generate',
    },
    {
        taskType: 'circle.summary.overlay.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'statistics_score',
        requiredCapabilities: ['text.generate'],
        allowedProviderProfiles: ['builtin', 'external'],
        promptVersion: 'v1',
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/circleSummary',
        aiJobType: null,
    },
    {
        taskType: 'voice.recap.rule.v1',
        catalogVersion: TASK_CATALOG_VERSION,
        status: 'current',
        executionStrategy: 'deterministic_only',
        requiredCapabilities: [],
        allowedProviderProfiles: [],
        promptVersion: null,
        outputSchemaVersion: 'v1',
        currentOwnerPath: 'services/query-api/src/services/voice/recap.ts',
        aiJobType: 'voice_recap_generate',
    },
];

const CATALOG_BY_JOB_TYPE = new Map<AiJobType, AiTaskCatalogEntry>(
    CURRENT_TASK_CATALOG
        .filter((entry): entry is AiTaskCatalogEntry & { aiJobType: AiJobType } => Boolean(entry.aiJobType))
        .map((entry) => [entry.aiJobType, entry]),
);

export function listAiTaskCatalogEntries(): AiTaskCatalogEntry[] {
    return CURRENT_TASK_CATALOG.map((entry) => ({
        ...entry,
        requiredCapabilities: [...entry.requiredCapabilities],
        allowedProviderProfiles: [...entry.allowedProviderProfiles],
    }));
}

export function resolveTaskCatalogEntry(taskType: string): AiTaskCatalogEntry | null {
    const entry = CURRENT_TASK_CATALOG.find((candidate) => candidate.taskType === taskType) ?? null;
    if (!entry) return null;
    return {
        ...entry,
        requiredCapabilities: [...entry.requiredCapabilities],
        allowedProviderProfiles: [...entry.allowedProviderProfiles],
    };
}

export function resolveTaskCatalogEntryForAiJobType(jobType: AiJobType): AiTaskCatalogEntry | null {
    const entry = CATALOG_BY_JOB_TYPE.get(jobType) ?? null;
    if (!entry) return null;
    return {
        ...entry,
        requiredCapabilities: [...entry.requiredCapabilities],
        allowedProviderProfiles: [...entry.allowedProviderProfiles],
    };
}
